website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))
    is_admin = db.Column(db.Boolean, default=False)


    reservations = db.relationship('Reservation', backref='user', lazy=True)


class Reservation(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    service = db.Column(db.String(150), nullable=False)
    date = db.Column(db.String(100), nullable=False)
    time = db.Column(db.String(100), nullable=False)
    created_at = db.Column(db.DateTime(timezone=True), server_default=func.now())

website/__init__.py
from flask import Flask, redirect, url_for, request
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager, current_user
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

db = SQLAlchemy()
DB_NAME = "database.db"


class AdminModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated and getattr(current_user, "is_admin", False)

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for("views.home", next=request.url))


def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "secretkey"
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DB_NAME}"
    db.init_app(app)

    from .views import views
    from .auth import auth
    from .models import User

    with app.app_context():
        db.create_all()
        admin = Admin(app, name="MyApp Admin", template_mode="bootstrap4")
        admin.add_view(AdminModelView(User, db.session))

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists("website/" + DB_NAME):
        db.create_all(app=app)
        print("Created Database!")

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   # from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/services')
def services():
    return render_template("services.html")

@auth.route('/contact')
def contact():
    return render_template("contact.html")

@auth.route('/about-us')
def about():
    return render_template("about.html")

@auth.route('/reservation')
@login_required
def reservation():
    if current_user.is_admin:
        from .models import Reservation
        reservations = Reservation.query.all()
        return render_template("admin_reservations.html", reservations=reservations, user=current_user)
    else:
        return render_template("reservation.html", user=current_user)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email') or ""
        first_name = request.form.get('firstName') or ""
        last_name = request.form.get('lastName') or ""
        password1 = request.form.get('password1') or ""
        password2 = request.form.get('password2') or ""

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif len(last_name) < 2:
            flash('Last name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(
                email=email,
                first_name=first_name,
                last_name=last_name,
                password=generate_password_hash(password1, method='pbkdf2:sha256')
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("signup.html", user=current_user)


@auth.route('/profile')
@login_required
def profile():
    return render_template("profile.html", user=current_user)


@auth.route('/delete-account', methods=['POST'])
@login_required
def delete_account():
    user = User.query.get(current_user.id)
    if user:
        logout_user()
        db.session.delete(user)
        db.session.commit()
        flash("Your account has been deleted.", "info")
    return redirect(url_for('views.home'))

@auth.route('/change-password', methods=['POST'])
@login_required
def change_password():
    current_password = request.form.get("current_password")
    new_password = request.form.get("new_password")
    confirm_password = request.form.get("confirm_password")

    if not check_password_hash(current_user.password, current_password):
        flash("Current password is incorrect.", category="error")
        return redirect(url_for("auth.profile"))

    if new_password != confirm_password:
        flash("New passwords do not match.", category="error")
        return redirect(url_for("auth.profile"))

    if len(new_password) < 7:
        flash("New password must be at least 7 characters long.", category="error")
        return redirect(url_for("auth.profile"))

    current_user.password = generate_password_hash(new_password, method="pbkdf2:sha256")
    db.session.commit()

    flash("Password updated successfully!", category="success")
    return redirect(url_for("auth.profile"))

website/views.py
from flask import Blueprint, render_template
from flask_login import  current_user


views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
def home():
    return render_template("home.html", user=current_user)

website/templates/about.html
{% extends "base.html" %} {% block title %}About Us{% endblock %}

website/templates/admin_reservations.html
{% extends "base.html" %}
{% block title %}All Reservations{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous" />
  <title>{% block title %}Home{% endblock %}</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style/base.css') }}">
</head>

<body> 
  <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top shadow-sm">
    <div class="container">
      <a class="navbar-brand" href="/">
        <img src="{{ url_for('static', filename='image/icon.png') }}" alt="Logo" width="80" height="80"
          class="d-inline-block align-top">
      </a>
      <button class="navbar-toggler d-lg-none" type="button" id="menuToggle">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse d-none d-lg-block" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto align-items-center">
          {% if current_user.is_authenticated %}
          {% if current_user.is_admin %}
          <li class="nav-item">
            <a class="nav-link text-dark px-4 fs-3" href="{{ url_for('auth.reservation') }}">All Reservations</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark px-4 fs-3 d-flex align-items-center" href="#" id="userDropdown"
              role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="fw-bolder me-2">Account</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="{{ url_for('auth.profile') }}">Profile</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item text-danger" href="{{ url_for('auth.logout') }}">Logout</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item"><a class="nav-link text-dark px-4 fs-3 fw-bolder" href="/">Home</a></li>
          <li class="nav-item"><a class="nav-link text-dark px-4 fs-3" href="/services">Services</a></li>
          <li class="nav-item"><a class="nav-link text-dark px-4 fs-3" href="/contact">Contact</a></li>
          <li class="nav-item"><a class="nav-link text-dark px-4 fs-3" href="/about-us">About Us</a></li>
          <li class="nav-item"><a class="nav-link text-dark px-4 fs-3"
              href="{{ url_for('auth.reservation') }}">Reservation</a></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark px-4 fs-3 d-flex align-items-center" href="#" id="userDropdown"
              role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="fw-bolder me-2">Account</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="{{ url_for('auth.profile') }}">Profile</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item text-danger" href="{{ url_for('auth.logout') }}">Logout</a>
            </div>
          </li>
          {% endif %}
          {% else %}
          <a class="nav-item nav-link text-dark px-4 fs-3 fw-bolder" href="/">Home</a>
          <a class="nav-item nav-link text-dark px-4 fs-3" href="/services">Services</a>
          <a class="nav-item nav-link text-dark px-4 fs-3" href="/contact">Contact</a>
          <a class="nav-item nav-link text-dark px-4 fs-3" href="/about-us">About Us</a>
          <a class="nav-item nav-link text-dark px-4 fs-3" href="/reservation">Reservation</a>
          <li class="nav-item"><a class="nav-link text-dark px-4 fs-3" href="/sign-up">Sign Up</a></li>
          <li class="nav-item"><a class="btn btn-outline-dark px-4 fs-4 ml-3" href="/login">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>


  <div id="bottomMenu" class="bottom-menu d-lg-none">
    <div class="menu-content text-center">
      <a href="/" class="d-block py-3 text-dark">Home</a>
      <a href="/services" class="d-block py-3 text-dark">Services</a>
      <a href="/contact" class="d-block py-3 text-dark">Contact</a>
      <a href="/about-us" class="d-block py-3 text-dark">About Us</a>
      <a href="/reservation" class="d-block py-3 text-dark">Reservation</a>
      <a href="/login" class="btn btn-dark btn-lg my-3">Login</a>
    </div>
  </div>

  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  {% if category == 'error' %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
  {% endwith %}

  <div class="container">{% block content %} {% endblock %}</div>


  <footer class="text-dark mt-5">
    <div class="container-fluid py-4">
      <div class="row mb-4">
        <div class="col-12 text-center">
          <p class="mb-0 fs-4"></p>
        </div>
      </div>
      <div class="row align-items-center">
      <div class="col-md-5 col-12 px-5 text-center text-md-start mb-4 mb-md-0">
        <img src="{{ url_for('static', filename='image/footer.png') }}" alt="Angelic Catering"
          class="img-fluid footer-img ml-5">
      </div>

        <div class="col-md-6 col-12 px-5">
          <div class="row justify-content-md-end text-center text-md-end">
            <div class="flex-column">
              <h5 class="mb-4"><a href="/" class="text-dark footer-link fs-1">Home</a></h5>
              <h5><a href="/contact" class="text-dark footer-link fs-1">Contact</a></h5>
            </div>
            <div class="d-none d-md-block col-2"></div>
            <div class="flex-column">
              <h5 class="mb-4"><a href="/services" class="text-dark footer-link fs-1">Services</a></h5>
              <h5><a href="/about-us" class="text-dark footer-link fs-1">About Us</a></h5>
            </div>
          </div>
        </div>
      </div>
      <div class="row mt-4 align-items-start">
        <div class="col-12 col-md-6 text-center text-md-start mb-3 mb-md-0">
          <p class="mb-2 fs-4">J. Romero Rd., Bagacay, Dumaguete City, Philippines</p>
        </div>
      <div class="col-12 col-md-5 text-right text-md-end">
        <p class="mb-0 fs-5">
          &copy; 2025 Angelic - Ann Foodhaus & Catering Services<br>
          All Rights Reserved.
        </p>
      </div>
      </div>
    </div>
  </footer>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <script>
    const menuToggle = document.getElementById('menuToggle');
    const bottomMenu = document.getElementById('bottomMenu');
    menuToggle.addEventListener('click', () => {
      bottomMenu.classList.toggle('show');
    });
    document.querySelectorAll('#bottomMenu a').forEach(link => {
      link.addEventListener('click', () => {
        bottomMenu.classList.remove('show');
      });
    });
  </script>
</body>

</html>

website/templates/contact.html
{% extends "base.html" %} {% block title %}Contact{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='style/home.css') }}">
<div class="container-fluid text-center px-0">
    <h1 class="cover-title mt-2 py-3">
        Angelic - Ann Foodhaus & Catering Services
    </h1>
    <img src="{{ url_for('static', filename='image/Cover.jpg') }}" alt="Cover"
        class="d-inline-block align-top mt-4 cover-img" />
    <div class="container my-5">
        <h1 class="my-4 font-weight-light">What We Offer</h1>
        <div class="offer-container mt-5">
            <div class="offer-card">
                <img src="{{ url_for('static', filename='image/Birthday.jpg') }}" alt="Birthday Party"
                    class="offer-img">
                <h2 class="offer-title">Birthday Party</h2>
                <p class="offer-desc">
                    Make birthdays extra special with customized menus, cakes, and fun party food.
                    From kids’ favorites to elegant adult celebrations, we serve dishes that match
                    the theme and mood.
                </p>
            </div>
            <div class="offer-card">
                <img src="{{ url_for('static', filename='image/Wedding.jpg') }}" alt="Wedding Reception"
                    class="offer-img">
                <h2 class="offer-title">Wedding Reception</h2>
                <p class="offer-desc">
                    Celebrate your big day with a grand feast. We provide full-course meals, buffet setups,
                    or plated dining with elegant presentation to make weddings unforgettable.
                </p>
            </div>
            <div class="offer-card">
                <img src="{{ url_for('static', filename='image/Christening2.jpg') }}" alt="Christening/Baptism"
                    class="offer-img">
                <h2 class="offer-title">Christening / Baptism</h2>
                <p class="offer-desc">
                    Celebrate this special milestone with a warm, family-style feast. We offer delicious
                    dishes and elegant setups to make your child's christening memorable and meaningful.
                </p>
            </div>
            <div class="offer-card">
                <img src="{{ url_for('static', filename='image/Graduation1.jpg') }}" alt="Graduation Celebration"
                    class="offer-img">
                <h2 class="offer-title">Graduation Celebration</h2>
                <p class="offer-desc">
                    Celebrate academic milestones with a festive spread. Our graduation menus feature
                    crowd-pleasing dishes perfect for friends, families, and classmates.
                </p>
            </div>
        </div>
        <h1 class="nav-service mt-5 py-3">
            Looking for more? Explore all our services
        </h1>
        <div style="text-align: start;">
            <a href="/services" class="explore-btn">See All Services</a>
        </div>
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="container mt-5" style="max-width: 400px;">
    <h2 class="mb-4 text-center">Login</h2>
    <form method="POST" action="/login">
        <div class="form-group mb-3">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>

        <div class="form-group mb-3">
            <label for="password">Password</label>
            <div class="input-group">
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                <button class="btn btn-outline-secondary" type="button" onclick="togglePassword('password')">
                    👁
                </button>
            </div>
        </div>

        <button type="submit" class="btn btn-dark w-100">Login</button>
    </form>
    <p class="text-center mt-3">
        Don’t have an account? <a href="/sign-up">Sign Up</a>
    </p>
</div>

<script>
    function togglePassword(fieldId) {
        const field = document.getElementById(fieldId);
        field.type = field.type === "password" ? "text" : "password";
    }
</script>
{% endblock %}

website/templates/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}

{% block content %}
<div class="container" style="max-width: 500px;">
    <h2 class="text-center mb-4">Account</h2>

    <div class="card shadow p-4">
        <p><strong>First Name:</strong> {{ user.first_name }}</p>
        <p><strong>Last Name:</strong> {{ user.last_name }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>

        <form method="POST" action="{{ url_for('auth.change_password') }}">
            <div class="mb-3">
                <label for="current_password" class="form-label">Current Password</label>
                <div class="input-group">
                    <input type="password" class="form-control" id="current_password" name="current_password" required>
                    <button class="btn btn-outline-secondary" type="button"
                        onclick="togglePassword('current_password')">
                        👁
                    </button>
                </div>
            </div>
            <div class="mb-3">
                <label for="new_password" class="form-label">New Password</label>
                <div class="input-group">
                    <input type="password" class="form-control" id="new_password" name="new_password" required>
                    <button class="btn btn-outline-secondary" type="button" onclick="togglePassword('new_password')">
                        👁
                    </button>
                </div>
            </div>
            <div class="mb-3">
                <label for="confirm_password" class="form-label">Confirm New Password</label>
                <div class="input-group">
                    <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
                    <button class="btn btn-outline-secondary" type="button"
                        onclick="togglePassword('confirm_password')">
                        👁
                    </button>
                </div>
            </div>
            <button type="submit" class="btn btn-outline-primary w-100 mb-3">Change Password</button>
        </form>

        <form method="POST" action="{{ url_for('auth.delete_account') }}">
            <button type="submit" class="btn btn-outline-danger w-100"
                onclick="return confirm('Are you sure you want to delete your account? This action cannot be undone.');">
                Delete Account
            </button>
        </form>
    </div>
</div>

<script>
    function togglePassword(fieldId) {
        const field = document.getElementById(fieldId);
        field.type = field.type === "password" ? "text" : "password";
    }
</script>
{% endblock %}

website/templates/reservation.html
{% extends "base.html" %} {% block title %}Reservation{% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}

<div class="container " style="max-width: 400px;">
    <h2 class="mb-4 text-center">Sign Up</h2>

    <form method="POST">
        <div class="mb-3">
            <label for="email" class="form-label">Email Address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="" required />
        </div>

        <div class="mb-3">
            <label for="firstName" class="form-label">First Name</label>
            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="" required />
        </div>

        <div class="mb-3">
            <label for="lastName" class="form-label">Last Name</label>
            <input type="text" class="form-control" id="lastName" name="lastName" placeholder="" required />
        </div>

        <div class="mb-3">
            <label for="password1" class="form-label">Password</label>
            <div class="input-group">
                <input type="password" class="form-control" id="password1" name="password1" placeholder="" required />
                <button class="btn btn-outline-secondary" type="button" onclick="togglePassword('password1')">
                    👁
                </button>
            </div>
        </div>

        <div class="mb-3">
            <label for="password2" class="form-label">Confirm Password</label>
            <div class="input-group">
                <input type="password" class="form-control" id="password2" name="password2" placeholder="" required />
                <button class="btn btn-outline-secondary" type="button" onclick="togglePassword('password2')">
                    👁
                </button>
            </div>
        </div>

        <button type="submit" class="btn btn-dark w-100">Sign Up</button>
    </form>

    <p class="text-center mt-3">
        Already have an account?
        <a href="/login">Login</a>
    </p>
</div>

<script>
    function togglePassword(fieldId) {
        const field = document.getElementById(fieldId);
        field.type = field.type === "password" ? "text" : "password";
    }
</script>

{% endblock %}